CREATE TABLE MERCHANT_FRAUD_HISTORY
   (
    rowId NUMBER NOT NULL ENABLE,
    USER_COD VARCHAR(50) NOT NULL ENABLE,
    PORTFOLIO VARCHAR2(5),
    ANALYSIS_DATE TIMESTAMP,
    ID_MERCHANT VARCHAR2(50),
    MERCHANT VARCHAR2(25),
    CITY VARCHAR2(40),
    COUNTRY_ISO VARCHAR2(3),
    COUNTRY VARCHAR2(3),
    MCC VARCHAR2(4),
    AMOUNT_LIMIT VARCHAR2(10),
    INTERVAL_DAYS NUMBER,
    TOTAL_FRAUD_APPROVED_AMOUNT NUMBER(9,2),
    FPI NUMBER,
    INVOLVED_CARDS_QTY NUMBER,
    BLOCKED_REVOKED_CARDS_QTY NUMBER,
    ENTRY_DATE TIMESTAMP,
    EXPIRATION_DATE TIMESTAMP,
    TYPE_MERCHANT VARCHAR2(20 BYTE),
    RULE_TYPE VARCHAR2(20 BYTE),
    ACTION VARCHAR2(50 BYTE),
    SPECIAL_CASE VARCHAR2(1 CHAR),
    SCORE_POINT NUMBER
   ) ;

   -- USE DB
   use jpa_test;
   
   -- CREATE TABLE 
   CREATE TABLE `merchant_fraud_history` (
   -- int
  `rowId` int(11) NOT NULL,
  -- string
  `USER_COD` varchar(20) DEFAULT NULL,
  `PORTFOLIO` varchar(20) DEFAULT NULL,
  -- timestamp
  `ANALYSIS_DATE` timestamp NULL DEFAULT NULL,
  -- Bigdecimal
  `TOTAL_FRAUD_APPROVED_AMOUNT` NUMERIC,
  
  `ID_MERCHANT` varchar(50) DEFAULT NULL,
  `MERCHANT` varchar(25) DEFAULT NULL,
  `CITY` varchar(40) DEFAULT NULL,
  `COUNTRY_ISO` varchar(10) DEFAULT NULL,
  `COUNTRY` varchar(10) DEFAULT NULL,
  `MCC` varchar(10) DEFAULT NULL,
  `AMOUNT_LIMIT` varchar(10) DEFAULT NULL,
  
  `FPI` int(11) DEFAULT NULL,
  `INTERVAL_DAYS` int(11) DEFAULT NULL,
  `INVOLVED_CARDS_QTY` int(11) DEFAULT NULL,
  `BLOCKED_REVOKED_CARDS_QTY` int(11) DEFAULT NULL,
  
  `TYPE_MERCHANT` varchar(10) DEFAULT NULL,
  `RULE_TYPE` varchar(10) DEFAULT NULL,
  
  `ACTION` varchar(50) DEFAULT NULL,
  
  `SPECIAL_CASE` varchar(2) DEFAULT NULL,
  
  `SCORE_POINT` NUMERIC
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- INSERT MERCHANT
INSERT INTO `jpa_test`.`merchant_fraud_history`
(`rowId`,
`USER_COD`,
`PORTFOLIO`,
`ANALYSIS_DATE`,
`TOTAL_FRAUD_APPROVED_AMOUNT`,

`ID_MERCHANT`,
`MERCHANT`,
`CITY`,
`COUNTRY_ISO`,
`COUNTRY`,
`MCC`,
`AMOUNT_LIMIT`,

`FPI`,
`INTERVAL_DAYS`,
`INVOLVED_CARDS_QTY`,
`BLOCKED_REVOKED_CARDS_QTY`,

`TYPE_MERCHANT`,
`RULE_TYPE`,

`ACTION`,
`SPECIAL_CASE`,
`SCORE_POINT`)
VALUES
(2,
"HAMID1",
"ITA",
'2018-02-01 00:00:01',
0,
-- ID_MERCHANT
"555555555555060",
-- MERCHANT
"ALL",
"ALL",
-- country_iso
"840",
"ITALY",
-- MCC
"0007",
">=0",

-- fpi
 52,
 90,
 25,
 13,
 
 -- type merchant
 "VERIFICA",
 "--",
 
 "here",
 "N",
 0
);
-- 2nd insertion
INSERT INTO `jpa_test`.`merchant_fraud_history`
(`rowId`,
`USER_COD`,
`PORTFOLIO`,
`ANALYSIS_DATE`,
`TOTAL_FRAUD_APPROVED_AMOUNT`,

`ID_MERCHANT`,
`MERCHANT`,
`CITY`,
`COUNTRY_ISO`,
`COUNTRY`,
`MCC`,
`AMOUNT_LIMIT`,

`FPI`,
`INTERVAL_DAYS`,
`INVOLVED_CARDS_QTY`,
`BLOCKED_REVOKED_CARDS_QTY`,

`TYPE_MERCHANT`,
`RULE_TYPE`,

`ACTION`,
`SPECIAL_CASE`,
`SCORE_POINT`)
VALUES
(3,"HAMID1","ITA",'2018-02-01 00:00:01',0,
-- ID_MERCHANT
"555555555555060",
-- MERCHANT
"ALL","ALL",
-- country_iso
"840","ITALY",
-- MCC
"0007",">=0",
-- fpi
 52, 90, 25, 13, 
 -- type merchant
 "VERIFICA", "--","here","Y",0);


-- ALTER the column varchar size
ALTER TABLE merchant_fraud_history MODIFY ID_MERCHANT VARCHAR(50);

-- ADD COLUMN TO MERCHANT
ALTER TABLE MERCHANT_FRAUD_HISTORY ADD SPECIAL_CASE varchar(5) DEFAULT NULL AFTER TOTAL_FRAUD_APPROVED_AMOUNT;

-- SELECT * MERCHANT
select * from merchant_fraud_history;

-- delete row

-- update row
UPDATE merchant_fraud_history SET `SPECIAL_CASE` = `N` WHERE ANALYSIS_DATE = '2018-02-01 00:00:01';

-- format of table
desc merchant_fraud_history ;