-- use db
use jpa_test;
-- create
CREATE TABLE `pv` (
  `id_pv` int(10) unsigned NOT NULL,
  `code` varchar(25) NOT NULL DEFAULT '"',
  `pref_mgis` varchar(5) DEFAULT NULL,
  `cod_mgis` int(10) unsigned DEFAULT NULL,
  `certificate` tinyint(1) DEFAULT NULL,
  `pv_m` tinyint(1) DEFAULT NULL,
  `client_is` tinyint(1) DEFAULT NULL,
  `client_code` varchar(25) DEFAULT NULL,
  `name1` varchar(50) DEFAULT NULL,
  `name2` varchar(50) DEFAULT NULL,
  `istat_id_tc` int(10) unsigned NOT NULL,
  `istat_id` int(11) unsigned DEFAULT NULL,
  `address` varchar(100) DEFAULT NULL,
  `cap` varchar(5) DEFAULT NULL,
  `comune` varchar(50) DEFAULT NULL,
  `provincia` char(2) DEFAULT NULL,
  `tel1` varchar(20) DEFAULT NULL,
  `tel2` varchar(20) DEFAULT NULL,
  `tel3` varchar(20) DEFAULT NULL,
  `cf_pi` varchar(20) DEFAULT NULL,
  `fax` varchar(20) DEFAULT NULL,
  `site` varchar(50) DEFAULT NULL,
  `email` varchar(51) DEFAULT NULL,
  `note` text,
  `updated_date` datetime DEFAULT NULL,
  `staet_id_tc` int(10) unsigned DEFAULT NULL,
  `ins_date` datetime DEFAULT NULL,
  `ins_user` int(10) unsigned DEFAULT NULL,
  `mod_date` datetime DEFAULT NULL,
  `mod_user` int(10) unsigned DEFAULT NULL,
  `psw` varchar(100) DEFAULT NULL,
  `first_to` tinyint(1) unsigned DEFAULT NULL,
  
  `presentation` tinyint(1) unsigned DEFAULT NULL,
  `newsletter` tinyint(1) unsigned DEFAULT NULL,
  `privacy` tinyint(1) unsigned DEFAULT NULL,
  `tc_state_other` tinyint(1) unsigned DEFAULT NULL,
  
  `note_for_disable` text,
  `exit_tel` varchar(4) DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `crypted_code` varchar(25) DEFAULT NULL,
  `coords` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id_pv`,`istat_id_tc`)
) ENGINE=InnoDB AUTO_INCREMENT=31445 DEFAULT CHARSET=utf8;

select * from pv;

-- insert 
INSERT INTO `jpa_test`.`pv`
(`id_pv`,
`code`,
`pref_mgis`,
`cod_mgis`,
`certificate`,
`pv_m`,
`client_is`,
`client_code`,
`name1`,
`name2`,
`istat_id_tc`,
`istat_id`,
`address`,
`cap`,
`comune`,
`provincia`,
`tel1`,
`tel2`,
`tel3`,
`cf_pi`,
`fax`,
`site`,
`email`,
`note`,
`updated_date`,
`staet_id_tc`,
`ins_date`,
`ins_user`,
`mod_date`,
`mod_user`,
`psw`,
`first_to`,
`presentation`,
`newsletter`,
`privacy`,
`tc_state_other`,
`note_for_disable`,
`exit_tel`,
`username`,
`crypted_code`,
`coords`)
VALUES
(1,
"FARM100517",
"FARM",
100517,
1,
1,
0,
1,
"far1",
"farm2",
5393,
37496,
"VIALE AVENTINO 78",
11122,
"ROMA",
"RM",
"tel1",
"<{tel2: }>",
"<{tel3: }>",
"<{cf_pi: }>",
"<{fax: }>",
"<{site: }>",
"<{email: }>",
"<{note: }>",
"2012-09-25 00:00:00",
1,
"2012-09-25 00:00:00",
1,
"2012-09-25 00:00:00",
1,
"<{psw: }>",
1,
0,
0,
0,
1,
"<{note_for_disable: }>",
"",
"<{username: }>",
"<{crypted_code: }>",
"<{coords: }>");
-- 2
INSERT INTO `jpa_test`.`pv`
(`id_pv`,
`code`,
`pref_mgis`,
`cod_mgis`,
`certificate`,
`pv_m`,
`client_is`,
`client_code`,
`name1`,
`name2`,
`istat_id_tc`,
`istat_id`,
`address`,
`cap`,
`comune`,
`provincia`,
`tel1`,
`tel2`,
`tel3`,
`cf_pi`,
`fax`,
`site`,
`email`,
`note`,
`updated_date`,
`staet_id_tc`,
`ins_date`,
`ins_user`,
`mod_date`,
`mod_user`,
`psw`,
`first_to`,
`presentation`,
`newsletter`,
`privacy`,
`tc_state_other`,
`note_for_disable`,
`exit_tel`,
`username`,
`crypted_code`,
`coords`)
VALUES
(2,
"FARM100517",
"FARM",
100517,
1,
1,
0,
1,
"far1",
"farm2",
5393,
37496,
"VIALE AVENTINO 78",
11122,
"ROMA",
"RM",
"tel1",
"<{tel2: }>",
"<{tel3: }>",
"<{cf_pi: }>",
"<{fax: }>",
"<{site: }>",
"<{email: }>",
"<{note: }>",
"2012-09-25 00:00:00",
1,
"2012-09-25 00:00:00",
1,
"2012-09-25 00:00:00",
1,
"<{psw: }>",
1,
0,
0,
0,
1,
"<{note_for_disable: }>",
"",
"<{username: }>",
"<{crypted_code: }>",
"<{coords: }>");

-- select All
INSERT INTO `jpa_test`.`pv`
(`id_pv`,
`code`,
`pref_mgis`,
`cod_mgis`,
`certificate`,
`pv_m`,
`client_is`,
`client_code`,
`name1`,
`name2`,
`istat_id_tc`,
`istat_id`,
`address`,
`cap`,
`comune`,
`provincia`,
`tel1`,
`tel2`,
`tel3`,
`cf_pi`,
`fax`,
`site`,
`email`,
`note`,
`updated_date`,
`staet_id_tc`,
`ins_date`,
`ins_user`,
`mod_date`,
`mod_user`,
`psw`,
`first_to`,
`presentation`,
`newsletter`,
`privacy`,
`tc_state_other`,
`note_for_disable`,
`exit_tel`,
`username`,
`crypted_code`,
`coords`)
VALUES
(1,
"FARM100517",
"FARM",
100517,
1,
1,
0,
1,
"far1",
"farm2",
5393,
37496,
"VIALE AVENTINO 78",
11122,
"ROMA",
"RM",
"tel1",
"<{tel2: }>",
"<{tel3: }>",
"<{cf_pi: }>",
"<{fax: }>",
"<{site: }>",
"<{email: }>",
"<{note: }>",
"2012-09-25 00:00:00",
1,
"2012-09-25 00:00:00",
1,
"2012-09-25 00:00:00",
1,
"<{psw: }>",
1,
0,
0,
0,
1,
"<{note_for_disable: }>",
"",
"<{username: }>",
"<{crypted_code: }>",
"<{coords: }>");

--
use jpa_test;
select * from pv;